### ISSUE TITLE
Discuss merits of switching to base fields

### ISSUE THREAD

**Issue by larowlan** [palantirnet/workbench_access#44]
Workbench moderation adds a new base field to the entity under moderation (moderation state).
Workbench access adds a configurable field (field_config).
Is there any reason why we can't use a base field here too.
It gives us more certainty in the code paths.
Thoughts?

**Comment by agentrickard** [comment]
I went back and forth on this in the D7 cycle. On the one hand, it's more predictable -- and we do it for test cases in D8, see the drush commands -- https://github.com/agentrickard/workbench_access/blob/8.x-1.x/workbench_access.drush.inc#L42.

On the other hand, the idea has been that people already have fields configured for their content model, so allowing that registration gives them more control over their architecture.

In the D7 version, I first wrote base fields and then added (at great effort) configurable fields. So in the D8 version I just went straight to configurable fields.

The other reason for that is because of the plugin architecture, it's not always clear what kind of field we should auto-create for people. We already have a working NodeReference plugin that isn't part of the core module.

Now that the variable field-handling code is done -- and we have methods like getEntityValues() -- there is no clear benefit to using base fields.

So I guess my answer is "but I already went through and coded for that uncertainty, so why remove it now"?

**Comment by larowlan** [comment]
Perfect answer.
And in thinking about the next project where I will need this module, there is already a vocabulary for 'Service area' which I could re-use as a section field.
And on that, I'll be helping out here as part of that project, so anything you want to point me towards as a matter of priority, point away.
As always - thanks for all your contributions.

**Comment by agentrickard** [comment]
Awesome. We have a very clear scope in the issues list, and it's pretty narrow, and divided by Alpha. Beta, and Final.

There are three things I would point to:
- We have almost no tests. And we need some.
- #25 Try extending to all content entities
- And whether we should rewrite the plugin API to return objects rather than arrays. I'm thinking specifically of the getTree() method, which returns a giant array of arrays, very Drupal 7.

**Comment by larowlan** [comment]
Tests are my thing, so will choose there first

On 4 May 2016 at 07:51, Ken Rickard notifications@github.com wrote:

> Awesome. We have a very clear scope in the issues list, and it's pretty
> narrow, and divided by Alpha. Beta, and Final.
> 
> There are three things I would point to:
> - We have almost no tests. And we need some.
> - #25 https://github.com/agentrickard/workbench_access/issues/25 Try
>   extending to all content entities
> - And whether we should rewrite the plugin API to return objects
>   rather than arrays. I'm thinking specifically of the getTree() method,
>   which returns a giant array of arrays, very Drupal 7.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/agentrickard/workbench_access/issues/44#issuecomment-216675845

## 

Lee Rowlands
Senior Drupal Developer
PreviousNext
skype: larowlan
email: larowlan@previousnext.com.au

**Comment by agentrickard** [comment]
You can probably model / rewrite the D7 tests, since I use SimpleTest for everything. I'm just not up on the new hotness.
