### ISSUE TITLE
Add cache context for user sections

### ISSUE THREAD

**Issue by acbramley** [palantirnet/workbench_access#72]
There are many cases where caching by sections would be beneficial.

I have a current use case where the workbench moderation form is cached on user.permissions but (now that https://www.drupal.org/node/2852717 is committed) a user without the edit permissions via WBA sections can incorrectly cache a node page, effectively hiding the form for users with the correct WBA section.

Spoke to @larowlan about this issue and he has suggested adding a cache context to the module based on a concatenated list of section ids for a user.

**Comment by agentrickard** [comment]
I'm not quite sure how caching of the node page matters here. Moderation actions are not under the scope of node access at the moment.

I was meaning to ask @larowlan about that, because I have a client feature request that asks for moderation to be covered by Workbench Access.

I'm looking at integration with core Content Moderation.

As far as I can tell, moderation is not handled by entity access (or the node access subset) at all. In fact, it looks like there is no clear way to alter the access check that produces the moderation form on entity view (which I think is what this original issue is about).

I once opened a security issue asking why moderation wasn't covered by node access and was given a difinitive answer that it was a separate operation from "update".  That's fine, but we don't seem to have the tools to modify the permission behavior the way we can with node access "update".

What am I missing here?

**Comment by larowlan** [comment]
A cache context is like a varnish 'vary' header. It can be attached to any cached item to say 'this item varies by x'. E.g. 'url' cache context says 'cache this per url'. Core has 'user' and 'user.permissions'. 'User' means cache per user and 'user.permissions' means 'cache per this unique combination of permissions'. Whilst we could use 'user' here, it is very granular and results in lots of cache entries. So the idea here is to add a context that is less granular than 'user' and is simply a list of section IDs, that way if two users belong to the same sections, there is only one cache entry that can be reused.

**Comment by agentrickard** [comment]
Right, sorry. I understand 'cache' context' -- my related question was around permission handling for access to the Content Moderation form outside the context of the edit page.

**Comment by larowlan** [comment]
Oh right - sorry - yeah in that instance we need to mirror the #access that is on that form element

Apologies if my comment was an insult

**Comment by agentrickard** [comment]
It's ok, I didn't take it personally. 

The #access that's in Workbench Moderation's handling of the form?

**Comment by agentrickard** [comment]
See #77 for the access piece. 

I'm confused about the original request -- what, if anything, is checking for access controls on the moderation form?

**Comment by agentrickard** [comment]
I see. That patch from the issue (https://www.drupal.org/node/2852717) only affects Workbench Moderation.  So I think parts of  PR #77 are redundant.

**Comment by acbramley** [comment]
We don't need the additional access checks, just a cache context that we can vary on. WBM and Content moderation's forms already limit on the access controls provided by WBA since we have `$build['workbench_moderation_control']['#access'] = $this->currentUser->hasPermission('moderate entities that cannot edit') || $entity->access('update');`

workbench_access_node_access() would be called during the $entity->access() call.

The problem here is that on my site, we have the moderation form displaying on the node view page as well as the latest revision page. Since there is no cache context for user sections, the page is cached via dynamic page cache (I believe) based on the user permissions. That means if an author hits the page that _can't_ edit/moderate it'll cache the page without the moderation form displayed. Then when an author with the correct WBA sections, or one with the `moderate entities that cannot edit` permission goes to the page, they can't see the form.

**Comment by agentrickard** [comment]
I've been testing on Content Moderation 8.3, which would probably explain why I didn't see this behavior in the module.

Can we get away with tagging the service with an existing cache tag, or do we need to introduce a new one entirely?

**Comment by agentrickard** [comment]
This is -- for the record -- why I don't like adding the moderation form via hook_entity_view(). We're now in a position where we have to handle custom page cache conditions any time a module introduces access controls on 'update' . 

So two problems:

* We can fix this for WA, but that doesn't help for other modules using hook_node_access(). Do each of those need to introduce their own cache condition now?
* We're going to explode the number of cache possibilities for storage and invalidation, perhaps making the page cache useless for nodes under access control.

If I understand correctly, WA would need to introduce a cache tag on the render array (using hook_entity_view_alter() and then also watch hook_entity_update() in order to invalidate tags.

That seems to me to be putting the burden of responsibility in the wrong place. 

The simple solution is adding a cache-by-user tag , but that wouldn't get invalidated when an entity is updated.

Would this be any better for cache performance  if the moderation form were a Block rather than embedded on entity view?

**Comment by agentrickard** [comment]
Could we just tag that element with 'user.roles:anonymous' for now and sort it later?

**Comment by larowlan** [comment]
I think you're mixing cache tags and cache contexts here. The entry would have the entity cache tags, so would be invalidated when the entity is updated. The context of user.wba_sections would tell make one entry per combination of user sections. Which is less granular than per user and possibly less granular than user role. I think acbramley may already have written this - I think it would be easier to have the conversation around some code than around concepts (personal preference).

**Comment by acbramley** [comment]
@larowlan my current workaround is to use a entity_view_alter and add the user cache context.

A cache context for user sections could be beneficial for other things, not just my edge-case.

**Comment by agentrickard** [comment]
Don't you have exactly the same cache issue if a user has "edit my Articles" vs. "edit any Articles"?

My point -- which may be wrong -- is that setting the proper cache invalidation tag is the responsibility of Moderation, not of the many, many modules that might alter edit permissions.

Put another way: Are we going to force every single node access module to provide a custom cache context?

**Comment by agentrickard** [comment]
I also don't think that a WA-specific cache context would be any more performant that cache-by-user.

**Comment by agentrickard** [comment]
I took a look through core code and think this is an area where core really has to intervene. The only provided context for this sort of operation is `user.nodegrants:operation`.

However, that context only deals with the Node Access (grants) system and lists of content. This is a recurring problem related to the introduction of hook_node_access() in Drupal 7, which makes generating accurate lists of editable content nearly impossible.

Forcing cache compliance down the line to contrib seems like a bad ideas here, as we'll just be playing whack-a-mole with related security issues as a result.

Better to be able to set a grant context at the core level. Perhaps tagging by implementation of hook_node_access() and account id.  Something like:

`user.node_access:module` 

Unfortunately, I think we need two arguments here `module` and `operation` and I don't think the context system supports that. We could handle that by splitting the operation into separate contexts:

* `user.node_access.view:module`
* `user.node_access.update:module`
* `user.node_access.delete:module`

Etc. These contexts would be added in cases where hook_node_access() is present beyond node_node_access().

I really think we need a test to see if changing the node permissions (edit own vs. edit any) causes a problem. Though perhaps it will not because that is cacheable per permission.

**Comment by agentrickard** [comment]
Closing for lack of a path forward.
